// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zmg.Infra.Data;

#nullable disable

namespace Zmg.Infra.Migrations
{
    [DbContext(typeof(ZmgDbContext))]
    [Migration("20260727135408_ReleaseTaskTranslations")]
    partial class ReleaseTaskTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zmg.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("MainArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Upc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainArtistId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxDaysBefore")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDaysBefore")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceTemplateTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ReleaseTasks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTaskTranslation", b =>
                {
                    b.Property<Guid>("ReleaseTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReleaseTaskId", "Locale");

                    b.ToTable("ReleaseTaskTranslations");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Isrc")
                        .HasColumnType("text");

                    b.Property<Guid>("MainArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainArtistId");

                    b.HasIndex("Title");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.SongArtist", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("SongArtists");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("MaxDaysBefore")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDaysBefore")
                        .HasColumnType("integer");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId", "Code");

                    b.ToTable("TemplateTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110100"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "mix-master",
                            Phase = 0,
                            SortOrder = 0,
                            Title = "Mix/master"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110201"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "design-cover",
                            Phase = 0,
                            SortOrder = 1,
                            Title = "Design cover for DSPs"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110302"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "distribute-to-dsps",
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 2,
                            Title = "Distribute to DSPs"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110403"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-video-assets",
                            Phase = 0,
                            SortOrder = 3,
                            Title = "Make video for YouTube, thumbnail and additional YouTube resources"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110504"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "pitch-amazon",
                            Phase = 0,
                            SortOrder = 4,
                            Title = "Pitch to Amazon"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110605"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "pitch-spotify",
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 5,
                            Title = "Pitch to Spotify"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110140"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "smart-link",
                            Phase = 1,
                            SortOrder = 0,
                            Title = "Setup smart link to all stores"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110241"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "smart-link-redirect",
                            Phase = 1,
                            SortOrder = 1,
                            Title = "Setup smart link redirect from zionmusicgroup.com/<song-name>"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110342"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "register-bmi",
                            Phase = 1,
                            SortOrder = 2,
                            Title = "Register composition to BMI"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110443"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "register-mlc",
                            Phase = 1,
                            SortOrder = 3,
                            Title = "Register composition to MLC"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110544"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "register-soundexchange",
                            Phase = 1,
                            SortOrder = 4,
                            Title = "Register to SoundExchange"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110645"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "musixmatch-lyrics",
                            Phase = 1,
                            SortOrder = 5,
                            Title = "Musixmatch lyrics, add/sync"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110746"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "check-deezer",
                            Phase = 1,
                            SortOrder = 6,
                            Title = "Check release in Deezer (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110847"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "check-amazon",
                            Phase = 1,
                            SortOrder = 7,
                            Title = "Check release in Amazon (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110948"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "check-apple",
                            Phase = 1,
                            SortOrder = 8,
                            Title = "Check release in Apple (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110a49"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "spotify-canvas",
                            Phase = 1,
                            SortOrder = 9,
                            Title = "Spotify Canvas"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110b4a"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "spotify-artist-pick",
                            Phase = 1,
                            SortOrder = 10,
                            Title = "Spotify Artist Pick"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110c4b"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-banner",
                            Phase = 1,
                            SortOrder = 11,
                            Title = "Update YouTube banner"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110d4c"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-home-video",
                            Phase = 1,
                            SortOrder = 12,
                            Title = "Update YouTube home video"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110e4d"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-cards",
                            Phase = 1,
                            SortOrder = 13,
                            Title = "Update cards in existing videos"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110f4e"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-pinned-comment",
                            Phase = 1,
                            SortOrder = 14,
                            Title = "Update pinned comment in existing videos with link to new video"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111104f"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "instagram-bio-youtube-link",
                            Phase = 1,
                            SortOrder = 15,
                            Title = "Update YouTube link on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111150"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "instagram-bio-song",
                            Phase = 1,
                            SortOrder = 16,
                            Title = "Update song on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111251"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "master-splits",
                            Phase = 1,
                            SortOrder = 17,
                            Title = "Send master splits to collaborators"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110180"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "meta-ads-initial",
                            Phase = 2,
                            SortOrder = 0,
                            Title = "Meta ads, initial release campaign"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110281"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "meta-ads-ongoing",
                            Phase = 2,
                            SortOrder = 1,
                            Title = "Meta ads, ongoing campaign"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110382"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "spotify-discovery-mode",
                            Phase = 2,
                            SortOrder = 2,
                            Title = "Spotify Discovery Mode"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110483"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-video-ads",
                            Phase = 2,
                            SortOrder = 3,
                            Title = "YouTube video ads"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110584"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "tiktok-ads",
                            Phase = 2,
                            SortOrder = 4,
                            Title = "TikTok ads"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110685"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "youtube-lyrics-video",
                            Phase = 2,
                            SortOrder = 5,
                            Title = "Create YouTube lyrics video"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110786"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "multitracks-setup",
                            Phase = 2,
                            SortOrder = 6,
                            Title = "Set up multitracks: Ableton project, Google Drive upload, new entry in zionmusicgroup.com/recursos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220100"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "mix-master",
                            Phase = 0,
                            SortOrder = 0,
                            Title = "Mix/master"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220201"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "design-cover",
                            Phase = 0,
                            SortOrder = 1,
                            Title = "Design cover for DSPs"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220302"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "distribute-to-dsps",
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 2,
                            Title = "Distribute to DSPs"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220403"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-video-assets",
                            Phase = 0,
                            SortOrder = 3,
                            Title = "Make video for YouTube, thumbnail and additional YouTube resources"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220504"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "pitch-amazon",
                            Phase = 0,
                            SortOrder = 4,
                            Title = "Pitch to Amazon"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220605"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "pitch-spotify",
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 5,
                            Title = "Pitch to Spotify"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220140"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "smart-link",
                            Phase = 1,
                            SortOrder = 0,
                            Title = "Setup smart link to all stores"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220241"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "smart-link-redirect",
                            Phase = 1,
                            SortOrder = 1,
                            Title = "Setup smart link redirect from zionmusicgroup.com/<song-name>"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220342"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "register-bmi",
                            Phase = 1,
                            SortOrder = 2,
                            Title = "Register composition to BMI"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220443"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "register-mlc",
                            Phase = 1,
                            SortOrder = 3,
                            Title = "Register composition to MLC"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220544"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "register-soundexchange",
                            Phase = 1,
                            SortOrder = 4,
                            Title = "Register to SoundExchange"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220645"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "musixmatch-lyrics",
                            Phase = 1,
                            SortOrder = 5,
                            Title = "Musixmatch lyrics, add/sync"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220746"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "check-deezer",
                            Phase = 1,
                            SortOrder = 6,
                            Title = "Check release in Deezer (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220847"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "check-amazon",
                            Phase = 1,
                            SortOrder = 7,
                            Title = "Check release in Amazon (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220948"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "check-apple",
                            Phase = 1,
                            SortOrder = 8,
                            Title = "Check release in Apple (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220a49"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "spotify-canvas",
                            Phase = 1,
                            SortOrder = 9,
                            Title = "Spotify Canvas"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220b4a"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "spotify-artist-pick",
                            Phase = 1,
                            SortOrder = 10,
                            Title = "Spotify Artist Pick"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220c4b"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-banner",
                            Phase = 1,
                            SortOrder = 11,
                            Title = "Update YouTube banner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220d4c"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-home-video",
                            Phase = 1,
                            SortOrder = 12,
                            Title = "Update YouTube home video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220e4d"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-cards",
                            Phase = 1,
                            SortOrder = 13,
                            Title = "Update cards in existing videos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220f4e"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-pinned-comment",
                            Phase = 1,
                            SortOrder = 14,
                            Title = "Update pinned comment in existing videos with link to new video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-22222222104f"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "instagram-bio-youtube-link",
                            Phase = 1,
                            SortOrder = 15,
                            Title = "Update YouTube link on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221150"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "instagram-bio-song",
                            Phase = 1,
                            SortOrder = 16,
                            Title = "Update song on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221251"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "master-splits",
                            Phase = 1,
                            SortOrder = 17,
                            Title = "Send master splits to collaborators"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220180"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "meta-ads-initial",
                            Phase = 2,
                            SortOrder = 0,
                            Title = "Meta ads, initial release campaign"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220281"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "meta-ads-ongoing",
                            Phase = 2,
                            SortOrder = 1,
                            Title = "Meta ads, ongoing campaign"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220382"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "spotify-discovery-mode",
                            Phase = 2,
                            SortOrder = 2,
                            Title = "Spotify Discovery Mode"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220483"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-video-ads",
                            Phase = 2,
                            SortOrder = 3,
                            Title = "YouTube video ads"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220584"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "tiktok-ads",
                            Phase = 2,
                            SortOrder = 4,
                            Title = "TikTok ads"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220685"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "youtube-lyrics-video",
                            Phase = 2,
                            SortOrder = 5,
                            Title = "Create YouTube lyrics video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220786"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "multitracks-setup",
                            Phase = 2,
                            SortOrder = 6,
                            Title = "Set up multitracks: Ableton project, Google Drive upload, new entry in zionmusicgroup.com/recursos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220706"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-tracklist-sequencing",
                            Phase = 0,
                            SortOrder = 6,
                            Title = "Finalize tracklist and sequencing (locked once submitted to distributor)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220807"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-isrc-upc-metadata",
                            Phase = 0,
                            SortOrder = 7,
                            Title = "Confirm ISRC/UPC and per-track metadata/credits"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220908"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-focus-tracks-waterfall",
                            Phase = 0,
                            SortOrder = 8,
                            Title = "Pick focus tracks and plan 2-4 pre-release singles (waterfall: each new single re-packaged with prior ones, album inherits their streams)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220a09"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-pre-save",
                            Phase = 0,
                            SortOrder = 9,
                            Title = "Album pre-save campaign"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220b0a"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-bio-press-epk",
                            Phase = 0,
                            SortOrder = 10,
                            Title = "Update artist bio / press release / EPK"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220c0b"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-batch-content",
                            Phase = 0,
                            SortOrder = 11,
                            Title = "Batch-produce content before release week (track-by-track commentary, lyric videos, acoustic cuts)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220d0c"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-physical-media",
                            Phase = 0,
                            SortOrder = 12,
                            Title = "Physical media if applicable (vinyl/CD lead times are months)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221352"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-per-track-registrations",
                            Phase = 1,
                            SortOrder = 18,
                            Title = "Registrations (BMI, MLC, Musixmatch, splits) repeat per track"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220887"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-rotate-focus-tracks",
                            Phase = 2,
                            SortOrder = 7,
                            Title = "Rotate focus tracks every few weeks with per-track playlist pitching"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220988"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "album-remaining-lyric-videos",
                            Phase = 2,
                            SortOrder = 8,
                            Title = "Lyric videos for remaining tracks"
                        });
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTaskTranslation", b =>
                {
                    b.Property<Guid>("TemplateTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TemplateTaskId", "Locale");

                    b.ToTable("TemplateTaskTranslations");

                    b.HasData(
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110100"),
                            Locale = "es",
                            Text = "Mezcla/master"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110201"),
                            Locale = "es",
                            Text = "Diseñar la portada para los DSPs"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110302"),
                            Locale = "es",
                            Text = "Distribuir a los DSPs"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110403"),
                            Locale = "es",
                            Text = "Hacer el video para YouTube, la miniatura y los demás recursos de YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110504"),
                            Locale = "es",
                            Text = "Pitch a Amazon"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110605"),
                            Locale = "es",
                            Text = "Pitch a Spotify"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110140"),
                            Locale = "es",
                            Text = "Configurar el smart link a todas las tiendas"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110241"),
                            Locale = "es",
                            Text = "Configurar la redirección del smart link desde zionmusicgroup.com/<song-name>"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110342"),
                            Locale = "es",
                            Text = "Registrar la composición en BMI"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110443"),
                            Locale = "es",
                            Text = "Registrar la composición en MLC"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110544"),
                            Locale = "es",
                            Text = "Registrar en SoundExchange"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110645"),
                            Locale = "es",
                            Text = "Letra en Musixmatch: agregar/sincronizar"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110746"),
                            Locale = "es",
                            Text = "Revisar el lanzamiento en Deezer (artista equivocado)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110847"),
                            Locale = "es",
                            Text = "Revisar el lanzamiento en Amazon (artista equivocado)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110948"),
                            Locale = "es",
                            Text = "Revisar el lanzamiento en Apple (artista equivocado)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110c4b"),
                            Locale = "es",
                            Text = "Actualizar el banner de YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110d4c"),
                            Locale = "es",
                            Text = "Actualizar el video destacado de YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110e4d"),
                            Locale = "es",
                            Text = "Actualizar las tarjetas en los videos existentes"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110f4e"),
                            Locale = "es",
                            Text = "Actualizar el comentario fijado en los videos existentes con el enlace al video nuevo"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-11111111104f"),
                            Locale = "es",
                            Text = "Actualizar el enlace de YouTube en las biografías de Instagram"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111111150"),
                            Locale = "es",
                            Text = "Actualizar la canción en las biografías de Instagram"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111111251"),
                            Locale = "es",
                            Text = "Enviar los master splits a los colaboradores"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110180"),
                            Locale = "es",
                            Text = "Meta ads: campaña inicial de lanzamiento"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110281"),
                            Locale = "es",
                            Text = "Meta ads: campaña continua"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110483"),
                            Locale = "es",
                            Text = "Anuncios de video en YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110584"),
                            Locale = "es",
                            Text = "Anuncios en TikTok"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110685"),
                            Locale = "es",
                            Text = "Crear el video con letra para YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("11111111-1111-1111-1111-111111110786"),
                            Locale = "es",
                            Text = "Preparar los multitracks: proyecto de Ableton, subida a Google Drive, nueva entrada en zionmusicgroup.com/recursos"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220100"),
                            Locale = "es",
                            Text = "Mezcla/master"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220201"),
                            Locale = "es",
                            Text = "Diseñar la portada para los DSPs"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220302"),
                            Locale = "es",
                            Text = "Distribuir a los DSPs"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220403"),
                            Locale = "es",
                            Text = "Hacer el video para YouTube, la miniatura y los demás recursos de YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220504"),
                            Locale = "es",
                            Text = "Pitch a Amazon"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220605"),
                            Locale = "es",
                            Text = "Pitch a Spotify"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220140"),
                            Locale = "es",
                            Text = "Configurar el smart link a todas las tiendas"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220241"),
                            Locale = "es",
                            Text = "Configurar la redirección del smart link desde zionmusicgroup.com/<song-name>"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220342"),
                            Locale = "es",
                            Text = "Registrar la composición en BMI"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220443"),
                            Locale = "es",
                            Text = "Registrar la composición en MLC"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220544"),
                            Locale = "es",
                            Text = "Registrar en SoundExchange"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220645"),
                            Locale = "es",
                            Text = "Letra en Musixmatch: agregar/sincronizar"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220746"),
                            Locale = "es",
                            Text = "Revisar el lanzamiento en Deezer (artista equivocado)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220847"),
                            Locale = "es",
                            Text = "Revisar el lanzamiento en Amazon (artista equivocado)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220948"),
                            Locale = "es",
                            Text = "Revisar el lanzamiento en Apple (artista equivocado)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220c4b"),
                            Locale = "es",
                            Text = "Actualizar el banner de YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220d4c"),
                            Locale = "es",
                            Text = "Actualizar el video destacado de YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220e4d"),
                            Locale = "es",
                            Text = "Actualizar las tarjetas en los videos existentes"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220f4e"),
                            Locale = "es",
                            Text = "Actualizar el comentario fijado en los videos existentes con el enlace al video nuevo"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-22222222104f"),
                            Locale = "es",
                            Text = "Actualizar el enlace de YouTube en las biografías de Instagram"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222221150"),
                            Locale = "es",
                            Text = "Actualizar la canción en las biografías de Instagram"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222221251"),
                            Locale = "es",
                            Text = "Enviar los master splits a los colaboradores"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220180"),
                            Locale = "es",
                            Text = "Meta ads: campaña inicial de lanzamiento"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220281"),
                            Locale = "es",
                            Text = "Meta ads: campaña continua"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220483"),
                            Locale = "es",
                            Text = "Anuncios de video en YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220584"),
                            Locale = "es",
                            Text = "Anuncios en TikTok"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220685"),
                            Locale = "es",
                            Text = "Crear el video con letra para YouTube"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220786"),
                            Locale = "es",
                            Text = "Preparar los multitracks: proyecto de Ableton, subida a Google Drive, nueva entrada en zionmusicgroup.com/recursos"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220706"),
                            Locale = "es",
                            Text = "Cerrar el tracklist y el orden de las canciones (queda fijo al enviarlo a la distribuidora)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220807"),
                            Locale = "es",
                            Text = "Confirmar ISRC/UPC y los metadatos/créditos de cada canción"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220908"),
                            Locale = "es",
                            Text = "Elegir los focus tracks y planear 2-4 sencillos previos al álbum (waterfall: cada sencillo nuevo se reempaqueta con los anteriores y el álbum hereda sus streams)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220a09"),
                            Locale = "es",
                            Text = "Campaña de pre-save del álbum"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220b0a"),
                            Locale = "es",
                            Text = "Actualizar la biografía del artista / el comunicado de prensa / el EPK"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220c0b"),
                            Locale = "es",
                            Text = "Producir contenido por lotes antes de la semana de lanzamiento (comentario canción por canción, videos con letra, versiones acústicas)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220d0c"),
                            Locale = "es",
                            Text = "Medios físicos si aplica (los tiempos de producción de vinilo/CD son de meses)"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222221352"),
                            Locale = "es",
                            Text = "Los registros (BMI, MLC, Musixmatch, splits) se repiten por cada canción"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220887"),
                            Locale = "es",
                            Text = "Rotar los focus tracks cada pocas semanas con pitching de playlists por canción"
                        },
                        new
                        {
                            TemplateTaskId = new Guid("22222222-2222-2222-2222-222222220988"),
                            Locale = "es",
                            Text = "Videos con letra para las canciones restantes"
                        });
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFocusTrack")
                        .HasColumnType("boolean");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasKey("ReleaseId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Release", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Artist", "MainArtist")
                        .WithMany("Releases")
                        .HasForeignKey("MainArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainArtist");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTask", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Release", "Release")
                        .WithMany("Tasks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTaskTranslation", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.ReleaseTask", "ReleaseTask")
                        .WithMany("Translations")
                        .HasForeignKey("ReleaseTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTask");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Song", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Artist", "MainArtist")
                        .WithMany("Songs")
                        .HasForeignKey("MainArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainArtist");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.SongArtist", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Artist", "Artist")
                        .WithMany("SongCredits")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zmg.Domain.Entities.Song", "Song")
                        .WithMany("Artists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTask", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("Tasks")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTaskTranslation", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.TemplateTask", "TemplateTask")
                        .WithMany("Translations")
                        .HasForeignKey("TemplateTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateTask");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Track", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zmg.Domain.Entities.Song", "Song")
                        .WithMany("ReleaseLinks")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Releases");

                    b.Navigation("SongCredits");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Release", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTask", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Song", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("ReleaseLinks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTask", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
