// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zmg.Infra.Data;

#nullable disable

namespace Zmg.Infra.Migrations
{
    [DbContext(typeof(ZmgDbContext))]
    [Migration("20260713162453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Zmg.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isrc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MainArtistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Upc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainArtistId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseArtist", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ReleaseArtists");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxDaysBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDaysBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceTemplateTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ReleaseTasks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChecklistTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxDaysBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDaysBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("TemplateTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110100"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 0,
                            SortOrder = 0,
                            Title = "Mix/master"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110201"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 0,
                            SortOrder = 1,
                            Title = "Design cover for DSPs"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110302"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 2,
                            Title = "Distribute to DSPs"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110403"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 0,
                            SortOrder = 3,
                            Title = "Make video for YouTube, thumbnail and additional YouTube resources"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110504"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 0,
                            SortOrder = 4,
                            Title = "Pitch to Amazon"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110605"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 5,
                            Title = "Pitch to Spotify"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110140"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 0,
                            Title = "Setup smart link to all stores"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110241"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 1,
                            Title = "Setup smart link redirect from zionmusicgroup.com/<song-name>"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110342"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 2,
                            Title = "Register composition to BMI"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110443"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 3,
                            Title = "Register composition to MLC"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110544"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 4,
                            Title = "Register to SoundExchange"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110645"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 5,
                            Title = "Musixmatch lyrics, add/sync"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110746"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 6,
                            Title = "Check release in Deezer (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110847"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 7,
                            Title = "Check release in Amazon (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110948"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 8,
                            Title = "Check release in Apple (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110a49"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 9,
                            Title = "Spotify Canvas"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110b4a"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 10,
                            Title = "Spotify Artist Pick"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110c4b"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 11,
                            Title = "Update YouTube banner"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110d4c"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 12,
                            Title = "Update YouTube home video"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110e4d"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 13,
                            Title = "Update cards in existing videos"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110f4e"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 14,
                            Title = "Update pinned comment in existing videos with link to new video"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111104f"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 15,
                            Title = "Update YouTube link on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111150"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 16,
                            Title = "Update song on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111251"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 1,
                            SortOrder = 17,
                            Title = "Send master splits to collaborators"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110180"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 0,
                            Title = "Meta ads, initial release campaign"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110281"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 1,
                            Title = "Meta ads, ongoing campaign"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110382"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 2,
                            Title = "Spotify Discovery Mode"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110483"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 3,
                            Title = "YouTube video ads"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110584"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 4,
                            Title = "TikTok ads"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110685"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 5,
                            Title = "Create YouTube lyrics video"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111110786"),
                            ChecklistTemplateId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phase = 2,
                            SortOrder = 6,
                            Title = "Set up multitracks: Ableton project, Google Drive upload, new entry in zionmusicgroup.com/recursos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220100"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 0,
                            Title = "Mix/master"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220201"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 1,
                            Title = "Design cover for DSPs"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220302"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 2,
                            Title = "Distribute to DSPs"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220403"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 3,
                            Title = "Make video for YouTube, thumbnail and additional YouTube resources"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220504"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 4,
                            Title = "Pitch to Amazon"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220605"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MaxDaysBefore = 14,
                            MinDaysBefore = 7,
                            Phase = 0,
                            SortOrder = 5,
                            Title = "Pitch to Spotify"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220140"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 0,
                            Title = "Setup smart link to all stores"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220241"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 1,
                            Title = "Setup smart link redirect from zionmusicgroup.com/<song-name>"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220342"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 2,
                            Title = "Register composition to BMI"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220443"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 3,
                            Title = "Register composition to MLC"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220544"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 4,
                            Title = "Register to SoundExchange"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220645"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 5,
                            Title = "Musixmatch lyrics, add/sync"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220746"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 6,
                            Title = "Check release in Deezer (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220847"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 7,
                            Title = "Check release in Amazon (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220948"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 8,
                            Title = "Check release in Apple (wrong artist)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220a49"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 9,
                            Title = "Spotify Canvas"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220b4a"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 10,
                            Title = "Spotify Artist Pick"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220c4b"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 11,
                            Title = "Update YouTube banner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220d4c"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 12,
                            Title = "Update YouTube home video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220e4d"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 13,
                            Title = "Update cards in existing videos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220f4e"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 14,
                            Title = "Update pinned comment in existing videos with link to new video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-22222222104f"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 15,
                            Title = "Update YouTube link on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221150"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 16,
                            Title = "Update song on Instagram bios"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221251"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 17,
                            Title = "Send master splits to collaborators"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220180"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 0,
                            Title = "Meta ads, initial release campaign"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220281"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 1,
                            Title = "Meta ads, ongoing campaign"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220382"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 2,
                            Title = "Spotify Discovery Mode"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220483"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 3,
                            Title = "YouTube video ads"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220584"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 4,
                            Title = "TikTok ads"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220685"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 5,
                            Title = "Create YouTube lyrics video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220786"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 6,
                            Title = "Set up multitracks: Ableton project, Google Drive upload, new entry in zionmusicgroup.com/recursos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220706"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 6,
                            Title = "Finalize tracklist and sequencing (locked once submitted to distributor)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220807"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 7,
                            Title = "Confirm ISRC/UPC and per-track metadata/credits"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220908"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 8,
                            Title = "Pick focus tracks and plan 2-4 pre-release singles (waterfall: each new single re-packaged with prior ones, album inherits their streams)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220a09"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 9,
                            Title = "Album pre-save campaign"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220b0a"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 10,
                            Title = "Update artist bio / press release / EPK"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220c0b"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 11,
                            Title = "Batch-produce content before release week (track-by-track commentary, lyric videos, acoustic cuts)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220d0c"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 0,
                            SortOrder = 12,
                            Title = "Physical media if applicable (vinyl/CD lead times are months)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221352"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 1,
                            SortOrder = 18,
                            Title = "Registrations (BMI, MLC, Musixmatch, splits) repeat per track"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220887"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 7,
                            Title = "Rotate focus tracks every few weeks with per-track playlist pitching"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220988"),
                            ChecklistTemplateId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phase = 2,
                            SortOrder = 8,
                            Title = "Lyric videos for remaining tracks"
                        });
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFocusTrack")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Release", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Artist", "MainArtist")
                        .WithMany("Releases")
                        .HasForeignKey("MainArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainArtist");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseArtist", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Artist", "Artist")
                        .WithMany("ReleaseCredits")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zmg.Domain.Entities.Release", "Release")
                        .WithMany("FeaturedArtists")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ReleaseTask", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Release", "Release")
                        .WithMany("Tasks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.TemplateTask", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("Tasks")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Track", b =>
                {
                    b.HasOne("Zmg.Domain.Entities.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Artist", b =>
                {
                    b.Navigation("ReleaseCredits");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Zmg.Domain.Entities.Release", b =>
                {
                    b.Navigation("FeaturedArtists");

                    b.Navigation("Tasks");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
